### ISSUE TITLE
ReferenceError: AndroidInitialContext is not defined

### ISSUE THREAD

**Issue by diegoaxity** [ionic-team/ionic-portals-react-native#44]
When using ver. 0.4.0 of react-native-ionic-portals, in combination with latest web based library @ionic/portals ver. 0.8.1, it crashes when trying to get initialContext on the web side, throwing this exception:

![Screenshot 2023-07-03 131431](https://github.com/ionic-team/react-native-ionic-portals/assets/39307881/57dfa502-6c81-4f98-bbd4-6db84bd6eade)

I suspect this error occurs because this library is not using the latest version of io.ionic:portals on the android native project.

It is currently using ver. "io.ionic:portals:0.7.+"

![Screenshot 2023-07-03 132049](https://github.com/ionic-team/react-native-ionic-portals/assets/39307881/ff8b6f51-ad94-4730-ae8a-690c3fa324e9)

Maybe it is fixable by upgrading to 0.8.+  in order to set/get initial context correctly.

**Comment by Steven0351** [comment]
This is expected, The React Native library has not yet been updated for `@ionic/portals@0.8.1`, you should still use `@ionic/portals@0.7.1`

**Comment by diegoaxity** [comment]
Thanks for your reply @Steven0351 , is there a plan for updating to `@ionic/portals@0.8.1`?

Version `0.7.1` is tied to capacitor 4, new projects using capacitor 5 can't use this version unless they are downgraded.

**Comment by Steven0351** [comment]
We do plan on updating, however we currently only have one paying customer using Portals for React Native and they're still on Capacitor 3 so this hasn't been our highest priority.

**Comment by Steven0351** [comment]
#47 closes this. Published as version 0.5.0.
